[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "project-name"
requires-python = ">=3.9"
description = "Project Description"
license = { file = "LICENSE" }
readme = {file = "README.md", content-type = "text/markdown"}
authors = [ { email = "<TBD@>", name = "<TBD>" } ]
maintainers = [ { email = "<TBD@>", name = "<TBD>" } ]
keywords = []
classifiers = [
    # https://pypi.org/classifiers/
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]
dependencies = []

[project.optional-dependencies]
dev = []
test = []

[project.urls]
homepage = "https://github.com/<TBD>"
Documentation = "https://github.com/<TBD>"
Repository = "https://github.com/<TBD>"
Changelog = "https://github.com/<TBD>/blob/master/CHANGELOG.md"

[project.scripts]
cli-name = "module.cli:main"

[tool.hatch.version]
path = "src/module/__about__.py"
